services:
  # Backend API Service
  - type: web
    name: realtor-rocket-api
    env: node
    plan: basic
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: realtor-rocket-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRES_IN
        value: 15m
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 10000

  # Frontend Service
  - type: web
    name: realtor-rocket-frontend
    env: static
    plan: basic
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: realtor-rocket-api
          property: host

databases:
  # PostgreSQL Database
  - name: realtor-rocket-db
    plan: basic
